services:
  db:
    image: ankane/pgvector  # Postgres с расширением pgvector
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  web:
    image: aliaksandr1403/plagiarism_detection:latest
    container_name: django_web
    command: gunicorn Folder.app.wsgi:application --bind 0.0.0.0:8000 --workers 3 --chdir /app/Folder
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    depends_on:
      - db
      - redis
    environment:
      - PYTHONPATH=/app/Folder
      - DEBUG=0
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery:
    image: aliaksandr1403/plagiarism_detection:latest
    container_name: celery_worker
    command: celery -A Folder.app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - PYTHONPATH=/app/Folder
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

volumes:
  pgvector_data:
